'use strict';

(function () {
  var ESC_KEYCODE = 27;

  var MAX_PERCENT = 100;
  var MIN_PERCENT = 25;
  var SHIFT_PERCENT = 25;
  var DEBOUNCE_INTERVAL = 500;

  window.constants = {
    ESC_KEYCODE: ESC_KEYCODE,

    MAX_PERCENT: MAX_PERCENT,
    MIN_PERCENT: MIN_PERCENT,
    SHIFT_PERCENT: SHIFT_PERCENT,
    DEBOUNCE_INTERVAL: DEBOUNCE_INTERVAL
  };
})();
